=== cristianosanchez/java-learning/src/test/resources/xml/phone.xsd
<xs:schema 	xmlns:xs='http://www.w3.org/2001/XMLSchema'>

<xs:complexType name="phoneType">
	<xs:simpleContent>
		<xs:extension base="xs:string">
			<xs:attribute name="location" type="xs:string" />
		</xs:extension>
	</xs:simpleContent>
</xs:complexType>

<xs:complexType name="personType">
	<xs:sequence>
		<xs:element name="name" type="xs:string" />
		<xs:element name="phone" type="phoneType" />
	</xs:sequence>
</xs:complexType>

<xs:element name="phone_book">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="person" type="personType" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== cristianosanchez/java-learning/src/test/resources/xml/phone.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- Each entry may contain a work, home, and mobile phone number -->
<phone_book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="phone.xsd">
	<person>
		<name>Jane Doe</name>
		<phone location="work">303-555-1212</phone>
	</person>
	<person>
		<name>John Smith</name>
		<phone location="home">301-555-1212</phone>
	</person>
	<person>
		<name>Joe Jones</name>
		<phone location="mobile">201-555-1212</phone>
	</person>
</phone_book>
